import { prismaClient } from './prisma-client';

export async function hospitalsSeed() {
  await prismaClient.hospital.createMany({
    data: [
      {
        name: 'istanbul hastanesi',
        address: 'sağlık caddesi no:123',
        city: 'istanbul',
        district: 'kadıköy',
        state: 'marmara',
        latitude: 43.0082,
        longitude: 24.9784,
        postalCode: '346064',
        phone: '+90 212 245 6482',
        email: 'info@ıstanbulhastanesı.com',
        website: 'www.ıstanbulhastanesı.com',
        hospitalCode: 'ISTANBUL_HASTANESİ',
      },
      {
        name: 'sağlık plus',
        address: 'wellness sokak no:456',
        city: 'ankara',
        district: 'çankaya',
        state: 'iç anadolu',
        latitude: 42.0082,
        longitude: 24.9784,
        postalCode: '344648',
        phone: '+90 212 843 4215',
        email: 'info@healthcareplus.com',
        website: 'www.healthcareplus.com',
        hospitalCode: 'SAĞLIK_PLUS',
      },
      {
        name: 'şehir hastanesi',
        address: 'bakım bulvarı no:789',
        city: 'izmir',
        district: 'konak',
        state: 'ege',
        latitude: 28.0082,
        longitude: 24.9784,
        postalCode: '341516',
        phone: '+90 212 404 4688',
        email: 'info@cityhospital.com',
        website: 'www.cityhospital.com',
        hospitalCode: 'ŞEHİR_HASTANESİ',
      },
      {
        name: 'büyük tıp merkezi',
        address: 'tıp caddesi no:101',
        city: 'antalya',
        district: 'muradpaşa',
        state: 'akdeniz',
        latitude: 43.0082,
        longitude: 22.9784,
        postalCode: '348088',
        phone: '+90 212 497 7324',
        email: 'info@grandmedicalcenter.com',
        website: 'www.grandmedicalcenter.com',
        hospitalCode: 'BÜYÜK_TIP_MERKEZİ',
      },
      {
        name: 'gündoğdu kliniği',
        address: 'iyileşme sokak no:202',
        city: 'bursa',
        district: 'nilüfer',
        state: 'marmara',
        latitude: 41.0082,
        longitude: 28.9784,
        postalCode: '344736',
        phone: '+90 212 670 4561',
        email: 'info@sunriseclinic.com',
        website: 'www.sunriseclinic.com',
        hospitalCode: 'GÜNDOĞDU_KLİNİĞİ',
      },
      {
        name: 'küresel sağlık',
        address: 'tedavi yolu no:303',
        city: 'adana',
        district: 'çukurova',
        state: 'akdeniz',
        latitude: 41.0082,
        longitude: 28.9784,
        postalCode: '341910',
        phone: '+90 212 117 2837',
        email: 'info@globalhealth.com',
        website: 'www.globalhealth.com',
        hospitalCode: 'KÜRESEL_SAĞLIK',
      },
      {
        name: 'birinci sınıf tıp hizmetleri',
        address: 'şifa caddesi no:404',
        city: 'konya',
        district: 'meram',
        state: 'iç anadolu',
        latitude: 41.0082,
        longitude: 28.9784,
        postalCode: '346751',
        phone: '+90 212 279 4194',
        email: 'info@primemedicalcare.com',
        website: 'www.primemedicalcare.com',
        hospitalCode: 'BİRİNCİ_SINIF_TIP_HİZMETLERİ',
      },
      {
        name: 'yıldız ışığı hastanesi',
        address: 'hayati sokak no:505',
        city: 'gaziantep',
        district: 'şahinbey',
        state: 'güneydoğu anadolu',
        latitude: 41.0082,
        longitude: 28.9784,
        postalCode: '348386',
        phone: '+90 212 475 9091',
        email: 'info@starlighthospital.com',
        website: 'www.starlighthospital.com',
        hospitalCode: 'YILDIZ_IŞIĞI_HASTANESİ',
      },
      {
        name: 'dadas sağlık kliniği',
        address: 'şifa bulvarı no:606',
        city: 'erzurum',
        district: 'ispir',
        state: 'doğu anadolu',
        latitude: 41.0082,
        longitude: 28.9784,
        postalCode: '341837',
        phone: '+90 212 258 9043',
        email: 'info@dadassaglık.com',
        website: 'www.dadassaglık.com',
        hospitalCode: 'DADAS_SAĞLIK_KLİNİĞİ',
      },
      {
        name: 'beyaz tıp merkezi',
        address: 'çare caddesi no:707',
        city: 'kayseri',
        district: 'melikgazi',
        state: 'iç anadolu',
        latitude: 41.0082,
        longitude: 28.9784,
        postalCode: '348004',
        phone: '+90 212 857 7474',
        email: 'info@beyaztıpmerkezı.com',
        website: 'www.beyaztıpmerkezı.com',
        hospitalCode: 'BEYAZ_TIP_MERKEZİ',
      },
    ],
    skipDuplicates: true,
  });
}
