import Generator from '@common/helpers/generator';
import { prismaClient } from './prisma-client';
import HashManager from '@common/helpers/hash-manager';
import { toZonedTime } from 'date-fns-tz';
export async function usersSeed() {
  const now = toZonedTime(new Date(), 'Europe/Istanbul');
  await prismaClient.user.createMany({
    data: [
      {
        userCode: Generator.random(8, 'numeric'),
        firstName: 'berat',
        lastName: 'azgun',
        fullName: 'berat azgun',
        gender: 'MALE',
        birthDate: now,
        email: 'beratazgun1@gmail.com',
        phone: '5387789862',
        password: await HashManager.hashPassword('Test1234!'),
        createdAt: now,
        updatedAt: now,
        isEmailVerified: true,
        verifiedAt: now,
      },
      {
        userCode: Generator.random(8, 'numeric'),
        firstName: 'berat',
        lastName: 'azgun',
        fullName: 'berat azgun',
        gender: 'MALE',
        birthDate: now,
        email: 'beratazgun2@gmail.com',
        phone: '5387789844',
        password: await HashManager.hashPassword('Test1234!'),
        createdAt: now,
        updatedAt: now,
        isEmailVerified: true,
        verifiedAt: now,
      },
      {
        userCode: Generator.random(8, 'numeric'),
        firstName: 'berat',
        lastName: 'azgun',
        fullName: 'berat azgun',
        gender: 'MALE',
        birthDate: now,
        email: 'beratazgun3@gmail.com',
        phone: '5387789664',
        password: await HashManager.hashPassword('Test1234!'),
        createdAt: now,
        updatedAt: now,
        isEmailVerified: true,
        verifiedAt: now,
      },
      {
        userCode: Generator.random(8, 'numeric'),
        firstName: 'berat',
        lastName: 'azgun',
        fullName: 'berat azgun',
        gender: 'MALE',
        birthDate: now,
        email: 'beratazgun4@gmail.com',
        phone: '5387789660',
        password: await HashManager.hashPassword('Test1234!'),
        createdAt: now,
        updatedAt: now,
        isEmailVerified: true,
        verifiedAt: now,
      },
      {
        userCode: Generator.random(8, 'numeric'),
        firstName: 'berat',
        lastName: 'azgun',
        fullName: 'berat azgun',
        gender: 'MALE',
        birthDate: now,
        email: 'beratazgun5@gmail.com',
        phone: '5387799664',
        password: await HashManager.hashPassword('Test1234!'),
        createdAt: now,
        updatedAt: now,
        isEmailVerified: false,
        verifiedAt: now,
      },
      {
        userCode: Generator.random(8, 'numeric'),
        firstName: 'berat',
        lastName: 'azgun',
        fullName: 'berat azgun',
        gender: 'MALE',
        birthDate: now,
        email: 'beratazgun6@gmail.com',
        phone: '5337789664',
        password: await HashManager.hashPassword('Test1234!'),
        createdAt: now,
        updatedAt: now,
        isEmailVerified: true,
        verifiedAt: now,
      },
      {
        userCode: Generator.random(8, 'numeric'),
        firstName: 'berat',
        lastName: 'azgun',
        fullName: 'berat azgun',
        gender: 'MALE',
        birthDate: now,
        email: 'beratazgun7@gmail.com',
        phone: '5330789664',
        password: await HashManager.hashPassword('Test1234!'),
        createdAt: now,
        updatedAt: now,
        isEmailVerified: false,
        verifiedAt: now,
      },
    ],
    skipDuplicates: true,
  });
}
